version = 0.1
[default.deploy.parameters]
stack_name = "LoggingServiceTest"
region = "eu-west-2"
profile = "courtsync"
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "logging-service-test"
