version = 0.1

[default.deploy.parameters]
stack_name = "InvoiceDelivery-test"
region = "eu-west-2"
profile = "courtsync"
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "invoicedelivery-test"
