version = 0.1
[default.deploy.parameters]
stack_name = "InvoiceDelivery-TEST"
resolve_s3 = true
s3_prefix = "InvoiceDelivery-TEST"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
