AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Notification Service for CourtSync

Globals:
  Function:
    Timeout: 30

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DailyInvoices-test
  
  ReadDailyInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ReadInvoices
      Handler: ReadInvoices.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonSQSFullAccess
      Environment:
        Variables:
          QUEUE_URL: !Ref MyQueue
          DATABASE_HOST: aws.connect.psdb.cloud
          DATABASE_USERNAME: eruwd8dh78reopyuxe7r
          DATABASE_PASSWORD: pscale_pw_PJEEbvW8to5ETnId5jaI0dLipcseLjLZ3bzyGMPZjF3
          DATABASE: main
      Events:
        ScheduleEvent:
            Type: Schedule
            Properties:
              Schedule: cron(0 8 * * ? *)
              Input: '{"view": "daily"}'

  ReadWeeklyInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ReadInvoices
      Handler: ReadInvoices.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonSQSFullAccess
      Environment:
        Variables:
          QUEUE_URL: !Ref MyQueue
          DATABASE_HOST: aws.connect.psdb.cloud
          DATABASE_USERNAME: eruwd8dh78reopyuxe7r
          DATABASE_PASSWORD: pscale_pw_PJEEbvW8to5ETnId5jaI0dLipcseLjLZ3bzyGMPZjF3
          DATABASE: main
      Events:
        ScheduleEvent:
            Type: Schedule
            Properties:
              Schedule: cron(0 8 ? * MON *)
              Input: '{"view": "weekly"}'

  ReadMonthlyInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ReadInvoices
      Handler: ReadInvoices.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonSQSFullAccess
      Environment:
        Variables:
          QUEUE_URL: !Ref MyQueue
          DATABASE_HOST: aws.connect.psdb.cloud
          DATABASE_USERNAME: eruwd8dh78reopyuxe7r
          DATABASE_PASSWORD: pscale_pw_PJEEbvW8to5ETnId5jaI0dLipcseLjLZ3bzyGMPZjF3
          DATABASE: main
      Events:
        ScheduleEvent:
            Type: Schedule
            Properties:
              Schedule: cron(0 8 1 * ? *)
              Input: '{"view": "monthly"}'

  SendInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/SendInvoices
      Handler: SendInvoices.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonSESFullAccess
      Environment:
        Variables:
          DATABASE_HOST: aws.connect.psdb.cloud
          DATABASE_USERNAME: eruwd8dh78reopyuxe7r
          DATABASE_PASSWORD: pscale_pw_PJEEbvW8to5ETnId5jaI0dLipcseLjLZ3bzyGMPZjF3
          DATABASE: main
          STRIPE_SECRET_KEY: sk_test_51O9ZfgHr5w2HXr5R8PQcEotoZ5FacJdXCm4yrAjWwjiFI9MkOwnqQLi6P2BBwYlrO5IeOZ7LznSW1oOBFdrV1Fci002J5POU5f
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn
            BatchSize: 10