AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Notification Service for CourtSync

Globals:
  Function:
    Timeout: 900
    Environment:
      Variables:
        DATABASE_HOST: aws.connect.psdb.cloud
        DATABASE_USERNAME: lhf8dq0lx4h84o26ym4j
        DATABASE_PASSWORD: pscale_pw_V1BteUKdqsKD8j723wRnkF548e0A0Zn0LKceMUbAhwO
        DATABASE: main
    Architectures:
      - arm64

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 900
      QueueName: DailyInvoices-test
  
  ReadDailyInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ReadInvoices
      Handler: ReadInvoices.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonSQSFullAccess
      Environment:
        Variables:
          QUEUE_URL: !Ref MyQueue
      Events:
        ScheduleEvent:
            Type: Schedule
            Properties:
              Schedule: cron(0 8 * * ? *)
              Input: '{"view": "daily"}'

  ReadWeeklyInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ReadInvoices
      Handler: ReadInvoices.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonSQSFullAccess
      Environment:
        Variables:
          QUEUE_URL: !Ref MyQueue
      Events:
        ScheduleEvent:
            Type: Schedule
            Properties:
              Schedule: cron(0 8 ? * MON *)
              Input: '{"view": "weekly"}'

  ReadMonthlyInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ReadInvoices
      Handler: ReadInvoices.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonSQSFullAccess
      Environment:
        Variables:
          QUEUE_URL: !Ref MyQueue
      Events:
        ScheduleEvent:
            Type: Schedule
            Properties:
              Schedule: cron(0 8 1 * ? *)
              Input: '{"view": "monthly"}'

  SendInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./SendInvoices
      Handler: SendInvoices.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonSESFullAccess
      Environment:
        Variables:
          STRIPE_SECRET_KEY: sk_test_51O9ZfgHr5w2HXr5R8PQcEotoZ5FacJdXCm4yrAjWwjiFI9MkOwnqQLi6P2BBwYlrO5IeOZ7LznSW1oOBFdrV1Fci002J5POU5f
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn
            BatchSize: 10