version = 0.1
[default.deploy.parameters]
stack_name = "NotificationsServiceTest"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "courtsync"
s3_bucket = "notification-service-test-bucket"
