version = 0.1
[default.deploy.parameters]
stack_name = "NotificationsService"
resolve_s3 = true
s3_prefix = "NotificationsService"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
