apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
      - name: invoice-container
        image: tennisdockerimages/invoice:v0.0.3
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: aws-cognito-secrets
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-invoice
spec:
  selector:
    app: invoice-service
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
