apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetable-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: timetable-service
  template:
    metadata:
      labels:
        app: timetable-service
    spec:
      containers:
      - name: timetable-container
        image: tennisdockerimages/timetable-container:v1.0.256
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: aws-cognito-secrets
        resources:
          requests:
            memory: "150Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-timetable
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: timetable-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: timetable-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: timetable-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50