apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: tennisdockerimages/authentication-container:v1.0.67
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: aws-cognito-secrets
        resources:
          requests:
            memory: "200Mi"
            cpu: "250"
          limits:
            memory: "300Mi"
            cpu: "250"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-auth
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: auth-service