name: Courtsync CI/CD

on:
  push:
    paths:
      - '**'

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2 # Replace with your AWS region

      - name: Update Secret ID in launch-script.sh
        run: |
          cd backend/API
          sed -i 's/YourSecretId/env-testing/g' launch-script.sh
          cd ../..

      - name: Sync with S3
        run: |
          aws s3 sync ./backend/API s3://courtsync-api-test

      - name: Reboot EC2 Instances
        run: |
          pip3 install -r update-requirements.txt
          python3 update.py

      - name: Build and Deploy Website
        run: |
          cd website
          cp test_env.txt .env
          npm install
          npm run build
          aws s3 sync build s3://test.courtsync.co.uk
