name: Authentication Container CI/CD

on:
  push:
    paths:
      - 'backend/Containers/InvoiceContainer/**'
  pull_request:
    paths:
      - 'backend/Containers/InvoiceContainer/**'

jobs:
    test-build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # Set up QEMU
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            # Install pytest
            - name: Install pytest
              run: |
                python -m pip install --upgrade pip
                pip install pytest

            - name: Install jq
              uses: dcarbone/install-jq-action@v2.1.0

            - name: Install requirements
              run: |
                pip install -r backend/Containers/InvoiceContainer/requirements.txt

            - name: Copy Shared Files
              run: |
                pip install -r backend/Containers/shared/requirements.txt
                cp -r backend/Containers/shared/src/* backend/Containers/InvoiceContainer/src/shared

            - name: Run Tests
              run: |
                cd backend/Containers/InvoiceContainer
                export PYTHONPATH=$PWD
                pytest
                cd ../../..
            
            - name: Build and Push Docker Image
              run: |
                cd backend/Containers/InvoiceContainer
                LATEST_TAG=$(curl -s https://registry.hub.docker.com/v2/repositories/tennisdockerimages/invoice/tags | jq -r '.results[].name' | grep -oE '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
                NEW_TAG=$(echo $LATEST_TAG | awk -F. -v OFS=. '{$NF = $NF + 1; print}')

                docker buildx build --platform linux/arm64 -t tennisdockerimages/invoice:$NEW_TAG --push .
